# Generated by Django 6.0 on 2026-01-30 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refund',
            name='status',
            field=models.CharField(choices=[('succeeded', 'Succeeded'), ('pending', 'Pending'), ('canceled', 'Canceled'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
    ]
