# Generated by Django 6.0 on 2026-02-02 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_alter_refund_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='updated_ad',
            new_name='updated_at',
        ),
    ]
