# Generated by Django 6.0 on 2026-02-02 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_rename_updated_ad_payment_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refund',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('failed', 'Failed'), ('canceled', 'Canceled'), ('succeeded', 'Succeeded')], default='pending', max_length=20),
        ),
    ]
